<a href="https://colab.research.google.com/github/agrillo91/MachineLearning_practice/blob/main/Prueba_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [414]:
import pandas as pd #biblioteca para el análisis y la manipulación de datos

In [415]:
dataset = pd.read_csv("titanic.csv") #leer datasets

In [416]:
dataset.head(10) #mostrar primeros 10 del dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [417]:
dataset.tail(10) #mostrar 10 últimos

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [418]:
dataset.describe() #genera un resumen estadístico de las columnas numéricas de un DataFrame o Series

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [419]:
dataset.info() #Muestra informacion sobre el dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [420]:
valores_faltantes = dataset.isna().sum() #valores no asignados y la cantidad
print(valores_faltantes)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [421]:
columnas_con_na = dataset.columns[dataset.isna().any()]
print(columnas_con_na)

Index(['Age', 'Cabin', 'Embarked'], dtype='object')

In [422]:
dataset.Embarked.value_counts() #Cuenta la cantidad de ocurrencias únicas de cada valor en la columna Embarked

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [423]:
#NA
dataset.Age.fillna(value=dataset.Age.mean()) # Establece en los valores NA la media de valores de la columna 'Age'
valores_faltantes = dataset.isna().sum()
print(valores_faltantes)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [424]:
dataset.Embarked.fillna(value=(dataset.Embarked.value_counts().idxmax())) #Llena los NA con el índice de mayor valor de la columna ‘Embarked’
columnas_con_na = dataset.columns[dataset.isna().any()]
print(columnas_con_na)

Index(['Age', 'Cabin', 'Embarked'], dtype='object')

In [425]:
dataset.Embarked.value_counts() #Ahora hay dos 'S' más que antes

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [426]:
fsiz = dataset.apply(lambda x: x.SibSp+x.Parch, axis=1) #Crear una Serie con la suma de SibSp y Parch
dataset['Family_Size'] = fsiz # Agrego la serie al DataFrame 'dataset' con el nombre de columna 'Family_Size'
dataset.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [427]:
dataset.drop('Parch', axis=1, inplace=True) #Eliminar columna 'Parch'
dataset.drop('SibSp', axis=1, inplace=True)
dataset.drop('Name', axis=1, inplace=True)
dataset.drop('Cabin', axis=1, inplace=True)
dataset.drop('Ticket', axis=1, inplace=True)
dataset.drop('PassengerId', axis=1, inplace=True)
dataset.head(3)

   Survived  Pclass     Sex   Age     Fare Embarked  Family_Size
0         0       3    male  22.0   7.2500        S            1
1         1       1  female  38.0  71.2833        C            1
2         1       3  female  26.0   7.9250        S            0

In [428]:
dataset.dtypes #muestra el tipo de dato de cada columna

Survived         int64
Pclass           int64
Sex             object
Age            float64
Fare           float64
Embarked        object
Family_Size      int64
dtype: object

In [429]:
for col in dataset.select_dtypes(exclude=["number"]).columns:
    print("Converting column "+col+"...")
    dataset[col] = dataset[col].astype('category')  #Convierte el tipo de dato en categórico
    print(dataset[col].cat.categories) #Este atributo devuelve las categorías únicas de la columna categórica.
    dataset[col] = dataset[col].cat.codes  #convierte las categorías en códigos numéricos.

Converting column Sex...
Index(['female', 'male'], dtype='object')
Converting column Embarked...
Index(['C', 'Q', 'S'], dtype='object')

In [430]:
dataset.dtypes

Survived         int64
Pclass           int64
Sex               int8
Age            float64
Fare           float64
Embarked          int8
Family_Size      int64
dtype: object

In [431]:
dataset.tail(3)

     Survived  Pclass  Sex   Age   Fare  Embarked  Family_Size
888         0       3    0   NaN  23.45         2            3
889         1       1    1  26.0  30.00         0            0
890         0       3    1  32.0   7.75         1            0

In [432]:
# Separar datos
Y = dataset['Survived'] #Almacenamos en 'Y' la columna 'Survived'
X = dataset.drop('Survived', axis=1) #Almacenamos en 'X' las filas del dataset - la columna 'Survived'

In [433]:
print(X.shape, Y.shape)

(891, 6) (891,)

In [434]:
# SCIKIT LEARN
import sklearn

In [435]:
# training y testing
from sklearn.model_selection import train_test_split

In [436]:
TRAIN_SIZE = 0.8
TESTING_SIZE = 0.2

In [437]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=TESTING_SIZE, random_state=42) #Separación para training y testing

In [438]:
print(x_train.shape, y_train.shape)

(712, 6) (712,)

In [439]:
print(x_test.shape, y_test.shape)

(179, 6) (179,)

In [440]:
# ARBOL DECISIONES  - DECISION TREE
from sklearn.tree import DecisionTreeClassifier
modelo_1 = DecisionTreeClassifier(random_state=0) #Crear arbol de decisiones

In [441]:
# RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
modelo_2 = RandomForestClassifier(n_estimators=15) # Crear Random Forest

In [442]:
# CROSS VALIDATION
from sklearn.model_selection import cross_val_score

In [443]:
scores_m1 = cross_val_score(modelo_1, X, Y, scoring="accuracy", cv=5) #Cross Validation
scores_m2 = cross_val_score(modelo_2, X, Y, scoring="accuracy", cv=5)

In [444]:
print(scores_m1)
print(scores_m2)

[0.74860335 0.78651685 0.80337079 0.73595506 0.79213483]
[0.78212291 0.78651685 0.84831461 0.78651685 0.83707865]

In [445]:
scores_m1.mean()

0.773316176009039

In [446]:
scores_m2.mean() #RandomForest muestra una mayor precision por validacion cruzada

0.8081099742640137

In [447]:
# ENTRENAMIENTO
modelo_1.fit(x_train, y_train) #Entrenar el modelo1
modelo_2.fit(x_train, y_train) #Entrenar modelo2

RandomForestClassifier(n_estimators=15)

In [448]:
print(modelo_1.score(x_train, y_train))
print(modelo_2.score(x_train, y_train))

0.9775280898876404
0.9705056179775281

In [449]:
# EVALUACION
#Testing dataset
print(modelo_1.score(x_test, y_test))
print(modelo_2.score(x_test, y_test))

0.7932960893854749
0.8044692737430168

In [450]:
# MATRIZ DE CONFUSION
from sklearn.metrics import confusion_matrix
y_pred_m1 = modelo_1.predict(x_test)
y_pred_m2 = modelo_2.predict(x_test)

In [451]:
confusion_matrix(y_test, y_pred_m1) #Generar matrix de confusion

array([[89, 16],
       [21, 53]])

In [452]:
confusion_matrix(y_test, y_pred_m2)

array([[89, 16],
       [19, 55]])